/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.1
 * Generated at: 2024-12-11 14:53:18 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;
import entidades.*;
import java.util.List;

public final class AddProducto_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(6);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("entidades");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = new java.util.LinkedHashSet<>(2);
    _jspx_imports_classes.add("java.util.List");
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>Ingresar producto</title>\r\n");
      out.write("    <link href=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	");
 if(session.getAttribute("listaCategoria")==null){
	
      out.write("\r\n");
      out.write("	<script> window.location.href=\"CategoriaServlet\"</script>\r\n");
      out.write("	");

}	

      out.write("\r\n");
      out.write("	 <div class=\"container mt-5\">\r\n");
      out.write("        <h2 class=\"text-center mb-4\">Agregar Producto</h2>\r\n");
      out.write("        <form action=\"AccionServlet?tipo=Ingresar\" id=\"productoForm\" method=\"post\">\r\n");
      out.write("        	<input type = \"hidden\" id = \"campoTipo\" name=\"tipo\" value=\"\">\r\n");
      out.write("            \r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"nombreProducto\" class=\"form-label\">Nombre del Producto</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"txtNombre\" id=\"nombreProducto\" placeholder=\"Nombre del producto\" >\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"descripcion\" class=\"form-label\">Descripción</label>\r\n");
      out.write("                <textarea class=\"form-control\" name=\"txtDescripcion\" id=\"descripcion\" rows=\"3\" placeholder=\"Descripción del producto\"></textarea>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"precio\" class=\"form-label\">Precio</label>\r\n");
      out.write("                <input type=\"number\" class=\"form-control\" name=\"txtPrecio\" id=\"precio\" step=\"0.01\" placeholder=\"Precio en soles\" >\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"cantidadStock\" class=\"form-label\">Cantidad en Stock</label>\r\n");
      out.write("                <input type=\"number\" class=\"form-control\" name=\"txtcantidadStock\" id=\"cantidadStock\" placeholder=\"Cantidad disponible\" >\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"cantidadMinima\" class=\"form-label\">Cantidad Mínima</label>\r\n");
      out.write("                <input type=\"number\" class=\"form-control\" name=\"txtcantidadMinima\" id=\"cantidadMinima\" placeholder=\"Cantidad mínima permitida\" >\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"idCategoria\"  class=\"form-label\">Categoría</label>\r\n");
      out.write("                <select class=\"form-select\" name=\"cboCategoria\" id=\"cboCategoria\" required>\r\n");
      out.write("                    <option selected disabled>Seleccione una categoría</option>\r\n");
      out.write("                    \r\n");
      out.write("                     ");
 List<Categorias> listaCategoria =(List<Categorias>) session.getAttribute("listaCategoria"); 
      out.write("\r\n");
      out.write("          		");
if(listaCategoria != null){
					for(Categorias item:listaCategoria){
				
      out.write("\r\n");
      out.write("						<option value=\"");
      out.print(item.getIdCategoria());
      out.write('"');
      out.write('>');
      out.print(item.getNombreCategoria() );
      out.write("</option>	\r\n");
      out.write("						");

					}
				}
				
      out.write("\r\n");
      out.write("                </select>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"marca\" class=\"form-label\">Marca</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"txtmarca\" id=\"marca\" placeholder=\"Marca del producto\" >\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"laboratorio\" class=\"form-label\">Laboratorio</label>\r\n");
      out.write("                <input type=\"text\" class=\"form-control\" name=\"txtlaboratorio\" id=\"laboratorio\" placeholder=\"Laboratorio o proveedor\" >\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"fechaIngreso\" class=\"form-label\">Fecha de Ingreso</label>\r\n");
      out.write("                <input type=\"date\" class=\"form-control\" name=\"txtfechaIngreso\" id=\"fechaIngreso\" >\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"fechaVencimiento\" class=\"form-label\">Fecha de Vencimiento</label>\r\n");
      out.write("                <input type=\"date\" class=\"form-control\" name=\"txtfechaVencimiento\" id=\"fechaVencimiento\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"descuento\" class=\"form-label\">Descuento (%)</label>\r\n");
      out.write("                <input type=\"number\" class=\"form-control\" name=\"txtdescuento\" id=\"descuento\" step=\"0.01\" placeholder=\"Descuento en porcentaje\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"mb-3\">\r\n");
      out.write("                <label for=\"imagen\" class=\"form-label\">Imagen</label>\r\n");
      out.write("                <input type=\"file\" class=\"form-control\" name=\"fileimagen\" id=\"imagen\" accept=\"image/*\">\r\n");
      out.write("            </div>\r\n");
      out.write("            <input type=\"submit\"  class=\"btn btn-primary w-100\"value=\"Ingresar\">\r\n");
      out.write("        </form>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Bootstrap JS -->\r\n");
      out.write("    <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
