/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/11.0.1
 * Generated at: 2024-12-18 16:34:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class Login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(4);
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>Login and Register</title>\r\n");
      out.write(" <link href=\"https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600;700&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("<script src=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("    body {\r\n");
      out.write("        font-family: 'Montserrat', sans-serif;\r\n");
      out.write("        margin: 0;\r\n");
      out.write("        padding: 0;\r\n");
      out.write("        background: linear-gradient(135deg, #e3f2fd, #90caf9);\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        align-items: center;\r\n");
      out.write("        min-height: 100vh;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .galvan {\r\n");
      out.write("        background: #ffffff;\r\n");
      out.write("        border-radius: 12px;\r\n");
      out.write("        box-shadow: 0 8px 16px rgba(0, 0, 0, 0.2);\r\n");
      out.write("        padding: 2rem;\r\n");
      out.write("        width: 400px;\r\n");
      out.write("        text-align: center;\r\n");
      out.write("        position: relative;\r\n");
      out.write("        animation: slide-in 1s ease-out;\r\n");
      out.write("        overflow: hidden;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    @keyframes slide-in {\r\n");
      out.write("        from {\r\n");
      out.write("            transform: translateY(-50px);\r\n");
      out.write("            opacity: 0;\r\n");
      out.write("        }\r\n");
      out.write("        to {\r\n");
      out.write("            transform: translateY(0);\r\n");
      out.write("            opacity: 1;\r\n");
      out.write("        }\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .admin-icon {\r\n");
      out.write("        margin-bottom: 1rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .admin-icon i {\r\n");
      out.write("        font-size: 3rem;\r\n");
      out.write("        color: #007bff;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        transition: transform 0.3s ease-in-out;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .admin-icon i:hover {\r\n");
      out.write("        transform: scale(1.2);\r\n");
      out.write("        color: #0056b3;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .galliquio {\r\n");
      out.write("        display: flex;\r\n");
      out.write("        justify-content: center;\r\n");
      out.write("        gap: 1rem;\r\n");
      out.write("        margin-bottom: 1.5rem;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .revoredo {\r\n");
      out.write("        text-decoration: none;\r\n");
      out.write("        font-weight: bold;\r\n");
      out.write("        color: #555;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        padding: 0.5rem 1rem;\r\n");
      out.write("        border-radius: 8px;\r\n");
      out.write("        transition: all 0.3s ease-in-out;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .revoredo.active {\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        background-color: #007bff;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .revoredo:hover {\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        background-color: #42a5f5;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .vargas {\r\n");
      out.write("        margin-bottom: 1rem;\r\n");
      out.write("        text-align: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .raymonda {\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        color: #444;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .torres {\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        padding: 0.8rem;\r\n");
      out.write("        border: 1px solid #ddd;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("        transition: all 0.3s;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .torres:focus {\r\n");
      out.write("        outline: none;\r\n");
      out.write("        border-color: #42a5f5;\r\n");
      out.write("        box-shadow: 0 0 5px rgba(66, 165, 245, 0.8);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hidalgo {\r\n");
      out.write("        background: #007bff;\r\n");
      out.write("        color: #fff;\r\n");
      out.write("        border: none;\r\n");
      out.write("        border-radius: 6px;\r\n");
      out.write("        padding: 0.8rem;\r\n");
      out.write("        width: 100%;\r\n");
      out.write("        cursor: pointer;\r\n");
      out.write("        font-size: 1rem;\r\n");
      out.write("        font-weight: 600;\r\n");
      out.write("        transition: background 0.3s ease-in-out;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .hidalgo:hover {\r\n");
      out.write("        background: #0056b3;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .admin-info {\r\n");
      out.write("        margin-top: 1rem;\r\n");
      out.write("        font-size: 0.9rem;\r\n");
      out.write("        color: #555;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .floating-image {\r\n");
      out.write("        position: absolute;\r\n");
      out.write("        top: -50px;\r\n");
      out.write("        left: 50%;\r\n");
      out.write("        transform: translateX(-50%);\r\n");
      out.write("        z-index: 1;\r\n");
      out.write("        width: 180px;\r\n");
      out.write("    }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("    <div class=\"galvan\">\r\n");
      out.write("        <div class=\"admin-icon\">\r\n");
      out.write("            <i class=\"fas fa-user-shield\" onclick=\"location.href='Principal.jsp'\"></i>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"galliquio\">\r\n");
      out.write("            <a href=\"#\" class=\"revoredo active\" id=\"tab-login\">Iniciar sesión</a>\r\n");
      out.write("            <a href=\"#\" class=\"revoredo\" id=\"tab-register\">Registrarse</a>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"login-section\">\r\n");
      out.write("            <form action=\"UsuarioServlet?action=login\" method=\"post\">\r\n");
      out.write("                <div class=\"vargas\">\r\n");
      out.write("                    <label for=\"email\" class=\"raymonda\">Correo electrónico</label>\r\n");
      out.write("                    <input type=\"email\" id=\"email\" name=\"email\" class=\"torres\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"vargas\">\r\n");
      out.write("                    <label for=\"password\" class=\"raymonda\">Contraseña</label>\r\n");
      out.write("                    <input type=\"password\" id=\"password\" name=\"password\" class=\"torres\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\" class=\"hidalgo\">Entrar</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"register-section\" style=\"display: none;\">\r\n");
      out.write("            <form action=\"UsuarioServlet?action=register\" method=\"post\">\r\n");
      out.write("                <div class=\"vargas\">\r\n");
      out.write("                    <label for=\"registerName\" class=\"raymonda\">Nombre</label>\r\n");
      out.write("                    <input type=\"text\" id=\"registerName\" name=\"name\" class=\"torres\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"vargas\">\r\n");
      out.write("                    <label for=\"registerEmail\" class=\"raymonda\">Correo electrónico</label>\r\n");
      out.write("                    <input type=\"email\" id=\"registerEmail\" name=\"email\" class=\"torres\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"vargas\">\r\n");
      out.write("                    <label for=\"registerPassword\" class=\"raymonda\">Contraseña</label>\r\n");
      out.write("                    <input type=\"password\" id=\"registerPassword\" name=\"password\" class=\"torres\" required>\r\n");
      out.write("                </div>\r\n");
      out.write("                <button type=\"submit\" class=\"hidalgo\">Registrarse</button>\r\n");
      out.write("            </form>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <script>\r\n");
      out.write("        document.getElementById(\"tab-login\").addEventListener(\"click\", function () {\r\n");
      out.write("            document.getElementById(\"login-section\").style.display = \"block\";\r\n");
      out.write("            document.getElementById(\"register-section\").style.display = \"none\";\r\n");
      out.write("            this.classList.add(\"active\");\r\n");
      out.write("            document.getElementById(\"tab-register\").classList.remove(\"active\");\r\n");
      out.write("        });\r\n");
      out.write("        document.getElementById(\"tab-register\").addEventListener(\"click\", function () {\r\n");
      out.write("            document.getElementById(\"register-section\").style.display = \"block\";\r\n");
      out.write("            document.getElementById(\"login-section\").style.display = \"none\";\r\n");
      out.write("            this.classList.add(\"active\");\r\n");
      out.write("            document.getElementById(\"tab-login\").classList.remove(\"active\");\r\n");
      out.write("        });\r\n");
      out.write("    </script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
